### ISSUE TITLE
How to modify it to make it to select multiple targets at the same time?

### ISSUE THREAD

**Issue by capitalwell** [OneNot/RelativeShortcutCreator#1]
Thanks for your nice jobs. But until now, it can only select one target when a dialog pop up. How to make it select multiple targets at the same time in one dialog? I'm not very farmilar with the syntax of AHK though.

**Comment by OneNot** [comment]
@capitalwell
The 'M' for multiselect flag of the [FileSelectFile method](https://www.autohotkey.com/docs/commands/FileSelectFile.htm) should let you select multiple files. You could then loop through the shortcut creation part of the script for each of the selected files.
[Here's a bit about the AHK language](https://www.autohotkey.com/docs/Language.htm)

Feel free to create a pull request if you decide to implement it if you'd like. If not, I might make the update myself later. :)

**Comment by capitalwell** [comment]
Thanks for your advice, and look forward to the update!

**Comment by OneNot** [comment]
Updated
